[package]
name = "atags-cli"
description = "Audio metadata command line tool encapsulating partial functions of audiotags"
author = "Syukkic@gmail.com"
version = "0.1.1"
edition = "2021"
license = "MIT"


[dependencies]
audiotags = "0.5.0"
clap = { version = "4.5.3", features = ["derive"] }
